# frozen_string_literal: true

RSpec.shared_examples 'buda responses' do
  let!(:buda_markets_response) do
    {"markets"=>
       [{"id"=>"BTC-CLP",
         "name"=>"btc-clp",
         "base_currency"=>"BTC",
         "quote_currency"=>"CLP",
         "minimum_order_amount"=>["0.00002", "BTC"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>nil,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"0.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"BTC-COP",
         "name"=>"btc-cop",
         "base_currency"=>"BTC",
         "quote_currency"=>"COP",
         "minimum_order_amount"=>["0.00002", "BTC"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>nil,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"0.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"ETH-CLP",
         "name"=>"eth-clp",
         "base_currency"=>"ETH",
         "quote_currency"=>"CLP",
         "minimum_order_amount"=>["0.001", "ETH"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>nil,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"0.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"ETH-BTC",
         "name"=>"eth-btc",
         "base_currency"=>"ETH",
         "quote_currency"=>"BTC",
         "minimum_order_amount"=>["0.001", "ETH"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>false,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"100.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"BTC-PEN",
         "name"=>"btc-pen",
         "base_currency"=>"BTC",
         "quote_currency"=>"PEN",
         "minimum_order_amount"=>["0.00002", "BTC"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>nil,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"0.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"ETH-PEN",
         "name"=>"eth-pen",
         "base_currency"=>"ETH",
         "quote_currency"=>"PEN",
         "minimum_order_amount"=>["0.001", "ETH"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>false,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"0.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"ETH-COP",
         "name"=>"eth-cop",
         "base_currency"=>"ETH",
         "quote_currency"=>"COP",
         "minimum_order_amount"=>["0.001", "ETH"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>nil,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"0.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"BCH-BTC",
         "name"=>"bch-btc",
         "base_currency"=>"BCH",
         "quote_currency"=>"BTC",
         "minimum_order_amount"=>["0.001", "BCH"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>false,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"100.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"BCH-CLP",
         "name"=>"bch-clp",
         "base_currency"=>"BCH",
         "quote_currency"=>"CLP",
         "minimum_order_amount"=>["0.001", "BCH"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>nil,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"0.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"BCH-COP",
         "name"=>"bch-cop",
         "base_currency"=>"BCH",
         "quote_currency"=>"COP",
         "minimum_order_amount"=>["0.001", "BCH"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>nil,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"0.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"BCH-PEN",
         "name"=>"bch-pen",
         "base_currency"=>"BCH",
         "quote_currency"=>"PEN",
         "minimum_order_amount"=>["0.001", "BCH"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>nil,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"0.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"BTC-ARS",
         "name"=>"btc-ars",
         "base_currency"=>"BTC",
         "quote_currency"=>"ARS",
         "minimum_order_amount"=>["0.00002", "BTC"],
         "disabled"=>true,
         "illiquid"=>false,
         "rpo_disabled"=>false,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"100.0",
         "taker_discount_percentage"=>"50.0"},
        {"id"=>"ETH-ARS",
         "name"=>"eth-ars",
         "base_currency"=>"ETH",
         "quote_currency"=>"ARS",
         "minimum_order_amount"=>["0.001", "ETH"],
         "disabled"=>true,
         "illiquid"=>false,
         "rpo_disabled"=>false,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"100.0",
         "taker_discount_percentage"=>"50.0"},
        {"id"=>"BCH-ARS",
         "name"=>"bch-ars",
         "base_currency"=>"BCH",
         "quote_currency"=>"ARS",
         "minimum_order_amount"=>["0.001", "BCH"],
         "disabled"=>true,
         "illiquid"=>false,
         "rpo_disabled"=>true,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"100.0",
         "taker_discount_percentage"=>"50.0"},
        {"id"=>"LTC-BTC",
         "name"=>"ltc-btc",
         "base_currency"=>"LTC",
         "quote_currency"=>"BTC",
         "minimum_order_amount"=>["0.003", "LTC"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>false,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"100.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"LTC-CLP",
         "name"=>"ltc-clp",
         "base_currency"=>"LTC",
         "quote_currency"=>"CLP",
         "minimum_order_amount"=>["0.003", "LTC"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>nil,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"0.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"LTC-COP",
         "name"=>"ltc-cop",
         "base_currency"=>"LTC",
         "quote_currency"=>"COP",
         "minimum_order_amount"=>["0.003", "LTC"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>nil,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"0.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"LTC-PEN",
         "name"=>"ltc-pen",
         "base_currency"=>"LTC",
         "quote_currency"=>"PEN",
         "minimum_order_amount"=>["0.003", "LTC"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>nil,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"0.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"LTC-ARS",
         "name"=>"ltc-ars",
         "base_currency"=>"LTC",
         "quote_currency"=>"ARS",
         "minimum_order_amount"=>["0.003", "LTC"],
         "disabled"=>true,
         "illiquid"=>false,
         "rpo_disabled"=>true,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"100.0",
         "taker_discount_percentage"=>"50.0"},
        {"id"=>"USDC-CLP",
         "name"=>"usdc-clp",
         "base_currency"=>"USDC",
         "quote_currency"=>"CLP",
         "minimum_order_amount"=>["0.01", "USDC"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>false,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"25.0",
         "taker_discount_percentage"=>"25.0"},
        {"id"=>"USDC-COP",
         "name"=>"usdc-cop",
         "base_currency"=>"USDC",
         "quote_currency"=>"COP",
         "minimum_order_amount"=>["0.01", "USDC"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>false,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"50.0",
         "taker_discount_percentage"=>"50.0"},
        {"id"=>"USDC-PEN",
         "name"=>"usdc-pen",
         "base_currency"=>"USDC",
         "quote_currency"=>"PEN",
         "minimum_order_amount"=>["0.01", "USDC"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>false,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"50.0",
         "taker_discount_percentage"=>"50.0"},
        {"id"=>"USDC-ARS",
         "name"=>"usdc-ars",
         "base_currency"=>"USDC",
         "quote_currency"=>"ARS",
         "minimum_order_amount"=>["0.01", "USDC"],
         "disabled"=>true,
         "illiquid"=>false,
         "rpo_disabled"=>false,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"100.0",
         "taker_discount_percentage"=>"50.0"},
        {"id"=>"BTC-USDC",
         "name"=>"btc-usdc",
         "base_currency"=>"BTC",
         "quote_currency"=>"USDC",
         "minimum_order_amount"=>["0.00002", "BTC"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>true,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"100.0",
         "taker_discount_percentage"=>"0.0"},
        {"id"=>"USDT-USDC",
         "name"=>"usdt-usdc",
         "base_currency"=>"USDT",
         "quote_currency"=>"USDC",
         "minimum_order_amount"=>["0.01", "USDT"],
         "disabled"=>false,
         "illiquid"=>false,
         "rpo_disabled"=>false,
         "taker_fee"=>0.8,
         "maker_fee"=>0.4,
         "max_orders_per_minute"=>100,
         "maker_discount_percentage"=>"100.0",
         "taker_discount_percentage"=>"100.0"}]}
  end
  let!(:btc_clp_order_book) do
    {
      "order_book": {
        "asks": [
          ["1000000","1"],
          ["62329003.0","0.166"]

        ],
        "bids": [
          ["900000","0.3742"],
          ["61799250.12","0.03236285"],
          ["1.0","149.4"]
        ],
        "market_id": "BTC-CLP"
      }
    }
  end

  let!(:markets_spreads_response) do
    {
      "spreads": {
        "BCH-ARS": "no_data_available",
        "BCH-BTC": 0.0031989800000000006,
        "BCH-CLP": 6205.809999999998,
        "BCH-COP": 217073,
        "BCH-PEN": 93.34000000000015,
        "BTC-ARS": "no_data_available",
        "BTC-CLP": 449752,
        "BTC-COP": 7740799.950000018,
        "BTC-PEN": 5950.059999999998,
        "BTC-USDC": 1050.830000000009,
        "ETH-ARS": "no_data_available",
        "ETH-BTC": 0.0011084500000000039,
        "ETH-CLP": 50363,
        "ETH-COP": 596126.9900000002,
        "ETH-PEN": 420.96000000000095,
        "LTC-ARS": "no_data_available",
        "LTC-BTC": 0.0001533699999999999,
        "LTC-CLP": 1152,
        "LTC-COP": 12880,
        "LTC-PEN": 11.21999999999997,
        "USDC-ARS": "no_data_available",
        "USDC-CLP": 4.240000000000009,
        "USDC-COP": 33.56999999999971,
        "USDC-PEN": 0.020000000000000018,
        "USDT-USDC": 0.0006000000000000449
      }
    }
  end
end